/**
 * Cluster Mode Types
 *
 * Types for AI-driven bulk article generation with interlinking.
 * Used exclusively for bulk/cluster generation - does not affect single article generation.
 */

import type { ArticleType } from '@/data/article-types';

// Title variation types (reuse from existing)
export type TitleVariation = 'question' | 'statement' | 'listicle';

/**
 * Input for cluster generation from the user
 */
export interface ClusterInput {
  topic: string;           // e.g., "Home Fitness"
  primaryKeyword: string;  // e.g., "home gym equipment"
  urlPattern: string;      // e.g., "/blog/{slug}"
  articleCount: number;    // 1-100
  variation: TitleVariation;       // Primary variation (first selected)
  variations?: TitleVariation[];   // All selected variations (multi-select)
}

/**
 * A single article in the cluster plan (AI-generated)
 */
export interface ClusterArticle {
  articleType: string;     // One of the 9 article type IDs
  title: string;           // AI-generated SEO title
  slug: string;            // Generated from title
  targetUrl: string;       // URL pattern with slug applied
  focus: string;           // What this article specifically covers
  keywords: string[];      // Semantic keywords for this article (for interlinking)
  isPillar: boolean;       // Whether this is the pillar (parent) article for the cluster
  variation?: TitleVariation; // Per-article variation (when AI chooses)
}

/**
 * Complete cluster plan generated by AI
 */
export interface ClusterPlan {
  topic: string;
  primaryKeyword: string;
  urlPattern: string;
  articles: ClusterArticle[];
  /** AI-generated interlinking plan with suggested anchor phrases per source→target pair */
  interlinkingPlan?: Array<{
    sourceIndex: number;
    targets: Array<{
      targetIndex: number;
      suggestedAnchorPhrases: string[];
    }>;
  }>;
}

/**
 * Target for interlinking - represents a sibling article to link to
 */
export type LinkStrategy = 'topic' | 'service' | 'location';

export interface InterlinkTarget {
  targetSlug: string;
  targetTitle: string;
  targetUrl: string;
  suggestedAnchorPhrases: string[];  // Keywords/phrases to match in content
  anchorTextType: 'exact' | 'semantic' | 'generic';
  linkStrategy?: LinkStrategy;       // topic|service|location per rules availability matrix
}

/**
 * A candidate position for inserting an interlink
 */
export interface InsertionCandidate {
  phrase: string;          // The matched text to turn into a link
  targetUrl: string;
  targetTitle: string;
  position: number;        // Character position in the HTML
  anchorType: 'exact' | 'semantic' | 'generic';
  paragraphIndex: number;
  wordPosition: number;    // Approximate word position for density checking
}

/**
 * Details about an inserted link
 */
export interface LinkDetail {
  anchorText: string;
  targetUrl: string;
  position: number;
  anchorType: 'exact' | 'semantic' | 'generic';
}

/**
 * Result of applying interlinking to an article
 */
export interface InterlinkingResult {
  modifiedHtml: string;
  linksInserted: number;
  linkDetails: LinkDetail[];
  relatedReadingAdded: boolean;
}

/**
 * Options for the interlinking service
 */
export interface InterlinkingOptions {
  articleHtml: string;
  wordCount: number;
  siblingArticles: ClusterArticle[];
  interlinkTargets: InterlinkTarget[];
  maxLinksOverride?: number;  // Optional override for max links
}

/**
 * Cluster context passed to article generation (optional - only for cluster mode)
 */
export interface ClusterContext {
  siblingArticles: Array<{
    title: string;
    url: string;
    focus: string;
    articleType: string;
  }>;
  interlinkKeywords: string[];  // Keywords from all siblings for natural referencing
}

/**
 * Metadata stored with each cluster article
 */
export interface ClusterArticleMetadata {
  clusterId: string;
  slug: string;
  targetUrl: string;
  interlinkingApplied: boolean;
  internalLinksInserted: number;
  relatedReadingAdded: boolean;
}

/**
 * Parsed paragraph from HTML for interlinking
 */
export interface ParsedParagraph {
  text: string;           // Plain text content
  html: string;           // Original HTML
  startPosition: number;  // Position in full HTML
  endPosition: number;
  index: number;
  wordCount: number;
}
