/**
 * Utility functions for exporting articles
 */

/**
 * Escape HTML special characters
 */
export function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Sanitize a string for use as a filename
 */
export function sanitizeFilename(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50);
}

/**
 * Wrap HTML content in a complete HTML document
 */
export function wrapInHtmlDocument(
  bodyContent: string,
  options: {
    title?: string;
    description?: string;
  } = {}
): string {
  const { title = "SCAI Article", description = "Generated by SCAI" } = options;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="${escapeHtml(description)}">
  <title>${escapeHtml(title)}</title>
  <style>
    /* Reset & Base */
    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }
    
    body {
      background: #ffffff;
      color: #111827;
      font-family: 'Georgia', 'Times New Roman', serif;
      line-height: 1.8;
    }
    
    article {
      max-width: 800px;
      margin: 0 auto;
      padding: 40px;
      min-height: 100vh;
    }
    
    /* Typography - Match preview styles exactly */
    h1 {
      font-size: 2.5rem;
      font-weight: 900;
      margin-bottom: 1.5rem;
      line-height: 1.1;
      color: #000;
      letter-spacing: -0.03em;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
    }
    
    h2 {
      font-size: 1.75rem;
      font-weight: 800;
      margin-top: 2.5rem;
      margin-bottom: 1.25rem;
      color: #000;
      letter-spacing: -0.02em;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
    }
    
    h3 {
      font-size: 1.25rem;
      font-weight: 700;
      margin-top: 1.5rem;
      margin-bottom: 0.75rem;
      color: #111;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Inter', sans-serif;
    }
    
    p {
      margin-bottom: 1.5rem;
      color: #374151;
      font-size: 1.1rem;
    }
    
    /* Lists */
    ul, ol {
      margin-bottom: 1.5rem;
      padding-left: 1.5rem;
      color: #374151;
    }
    
    li {
      margin-bottom: 0.5rem;
    }
    
    /* Images */
    img {
      max-width: 100%;
      height: auto;
      max-height: 400px;
      width: 100%;
      object-fit: cover;
      border-radius: 20px;
      margin: 2rem 0;
      box-shadow: 0 4px 20px -4px rgba(0, 0, 0, 0.1);
    }
    
    /* Blockquotes */
    blockquote {
      border-left: 4px solid #000;
      padding-left: 1.5rem;
      font-style: italic;
      color: #4B5563;
      margin: 2rem 0;
    }
    
    /* Tables */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 2rem 0;
      font-size: 0.95rem;
    }
    
    th, td {
      padding: 0.75rem 1rem;
      border: 1px solid #E5E7EB;
      text-align: left;
    }
    
    th {
      background-color: #F9FAFB;
      font-weight: 700;
    }
    
    /* Print styles */
    @media print {
      body {
        background: white;
      }
      
      article {
        padding: 20px;
      }
      
      img {
        page-break-inside: avoid;
      }
    }
  </style>
</head>
<body>
  <article>
${bodyContent}
  </article>
</body>
</html>`;
}

/**
 * Download HTML content as a file
 */
export function downloadHtmlFile(
  html: string,
  filename: string,
  wrapAsDocument = false,
  documentOptions?: { title?: string; description?: string }
): void {
  const content = wrapAsDocument ? wrapInHtmlDocument(html, documentOptions) : html;
  const blob = new Blob([content], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename.endsWith(".html") ? filename : `${filename}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
