/**
 * Article Generation Orchestration Task
 * 
 * Trigger.dev parent task that coordinates the full article generation:
 * 1. Generate article structure and content (text)
 * 2. Extract image placeholders from HTML
 * 3. Batch trigger image generation tasks
 * 4. Assemble final HTML with R2 URLs
 * 5. Validate and correct alt texts
 * 
 * This runs as a background job, freeing the Vercel function from timeouts.
 */

import { task, logger } from "@trigger.dev/sdk";
import { db } from "@/lib/db";
import { generationHistory, generationJobs } from "@/lib/db/schema";
import { eq } from "drizzle-orm";
import { createProgressHelper } from "@/lib/services/pusher-server";
import { generateImageTask } from "./generate-images";
import { correctAltTextsInHtml } from "@/lib/services/content-corrector";
import { createCostTrackingContext, updateGenerationCostSummary } from "@/lib/services/cost-tracking-service";
import { refundCredits } from "@/lib/services/credit-service";
import { IMAGE_CREDIT_RATES } from "@/lib/services/credit-estimator";
import type { ArticleType, ImageType, ImageProvider } from "@/lib/services/imagen";
import type { AIProvider } from "@/lib/ai/providers";

// ═══════════════════════════════════════════════════════════════════════════════
// TYPES
// ═══════════════════════════════════════════════════════════════════════════════

export interface OrchestrationPayload {
  /** Unique job ID */
  jobId: string;
  /** User ID */
  userId: string;
  /** Pre-generated history record ID */
  historyId: string;
  /** Article type */
  articleType: ArticleType;
  /** Topic/keyword */
  topic: string;
  /** Target word count */
  targetWordCount: number;
  /** HTML content with image placeholders (generated by Vercel function) */
  htmlWithPlaceholders: string;
  /** Word count of the content */
  wordCount: number;
  /** Image placeholders extracted from HTML */
  imagePlaceholders: ImagePlaceholder[];
  /** Variation name used */
  variationName?: string;
  /** Provider used for content generation */
  provider?: string;
  /** Skip image generation (dev mode only) */
  skipImages?: boolean;
  /** Image provider to use (gemini or flux) */
  imageProvider?: ImageProvider;
  /** Estimated credits deducted at start */
  estimatedCredits?: number;
}

export interface ImagePlaceholder {
  /** Unique ID for this image */
  imageId: string;
  /** The placeholder text in HTML (e.g., {{IMAGE:description}}) */
  placeholder: string;
  /** Human-readable description/prompt */
  description: string;
  /** Image type */
  imageType: ImageType;
  /** Component type for metadata */
  componentType?: string;
  /** Article context for better generation */
  context?: string;
  /** Step number for how-to articles */
  stepNumber?: number;
  /** Optional source image URL for transformation (Amazon product image) */
  sourceImageUrl?: string;
  /** Matched product name for reference image context */
  sourceProductName?: string;
}

export interface OrchestrationResult {
  success: boolean;
  historyId: string;
  finalHtml?: string;
  wordCount: number;
  imageCount: number;
  successfulImages: number;
  failedImages: number;
  error?: string;
}

// ═══════════════════════════════════════════════════════════════════════════════
// ORCHESTRATION TASK
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Main orchestration task for article generation
 * 
 * The Vercel serverless function handles:
 * - Auth validation
 * - Structure generation
 * - Content streaming via SSE (immediate user feedback)
 * - Extracting image placeholders
 * - Triggering this background job
 * 
 * This task handles:
 * - Parallel image generation via child tasks
 * - R2 uploads
 * - Final HTML assembly
 * - Database updates
 * - Real-time progress via Pusher
 */
export const orchestrateGenerationTask = task({
  id: "orchestrate-generation",
  // Allow up to 10 minutes for full orchestration
  machine: {
    preset: "medium-1x", // 2 vCPU, 4GB RAM
  },
  retry: {
    maxAttempts: 2,
    minTimeoutInMs: 5000,
    maxTimeoutInMs: 60000,
  },
  run: async (payload: OrchestrationPayload): Promise<OrchestrationResult> => {
    const {
      jobId,
      userId,
      historyId,
      articleType,
      topic,
      htmlWithPlaceholders,
      wordCount,
      imagePlaceholders,
      skipImages = false,
    } = payload;

    logger.info("Starting article orchestration", {
      jobId,
      historyId,
      articleType,
      topic,
      imageCount: imagePlaceholders.length,
      skipImages,
    });

    const progress = createProgressHelper(jobId, userId);

    try {
      // Update job status to running
      await db.update(generationJobs)
        .set({
          status: "running",
          phase: "images",
          startedAt: new Date(),
          totalImages: imagePlaceholders.length,
          updatedAt: new Date(),
        })
        .where(eq(generationJobs.id, jobId));

      // Notify: starting image generation phase
      await progress.phase("images", 10);

      // Skip image generation if flag is set (dev mode only)
      if (skipImages) {
        logger.info("Skipping image generation (dev mode)");

        await finalizeArticle(historyId, htmlWithPlaceholders, wordCount, 0, 0);

        // Note: finalHtml is omitted to avoid Pusher's 10KB payload limit
        // Frontend falls back to prev.html which already has the content
        await progress.complete({
          historyId,
          wordCount,
          imageCount: 0,
          successfulImages: 0,
          failedImages: 0,
        });

        return {
          success: true,
          historyId,
          finalHtml: htmlWithPlaceholders,
          wordCount,
          imageCount: 0,
          successfulImages: 0,
          failedImages: 0,
        };
      }

      if (imagePlaceholders.length === 0) {
        // No images to generate, just finalize
        logger.info("No images to generate, finalizing article");

        await finalizeArticle(historyId, htmlWithPlaceholders, wordCount, 0, 0);

        // Note: finalHtml is omitted to avoid Pusher's 10KB payload limit
        // Frontend falls back to prev.html which already has the content
        await progress.complete({
          historyId,
          wordCount,
          imageCount: 0,
          successfulImages: 0,
          failedImages: 0,
        });

        return {
          success: true,
          historyId,
          finalHtml: htmlWithPlaceholders,
          wordCount,
          imageCount: 0,
          successfulImages: 0,
          failedImages: 0,
        };
      }

      // ─────────────────────────────────────────────────────────────────────────
      // BATCH TRIGGER IMAGE GENERATION TASKS
      // ─────────────────────────────────────────────────────────────────────────
      logger.info(`Triggering ${imagePlaceholders.length} image generation tasks`);

      const imagePayloads = imagePlaceholders.map((placeholder, index) => ({
        payload: {
          imageId: placeholder.imageId,
          historyId,
          userId,
          jobId,
          prompt: placeholder.description,
          context: placeholder.context || topic,
          imageType: placeholder.imageType,
          articleType,
          componentType: placeholder.componentType,
          stepNumber: placeholder.stepNumber,
          sourceImageUrl: placeholder.sourceImageUrl,
          sourceProductName: placeholder.sourceProductName,
          index: index + 1, // 1-indexed to match placeholder URLs (Loading+Image+1, etc.)
          total: imagePlaceholders.length,
          imageProvider: payload.imageProvider,
        },
      }));

      // Use batchTriggerAndWait to run all image tasks in parallel and wait for completion
      const batchResult = await generateImageTask.batchTriggerAndWait(imagePayloads);

      // Process results
      let successfulImages = 0;
      let failedImages = 0;
      const imageUrlMap = new Map<string, string>();

      for (const result of batchResult.runs) {
        if (result.ok && result.output.success) {
          successfulImages++;
          imageUrlMap.set(result.output.imageId, result.output.url!);
          logger.info("Image generated successfully", { imageId: result.output.imageId });
        } else {
          failedImages++;
          const output = result.ok ? result.output : null;
          // Find the placeholder for this result
          const placeholder = imagePlaceholders.find(p =>
            imagePayloads.find(ip => ip.payload.imageId === (output?.imageId || p.imageId))
          );
          const isProductCard = placeholder?.componentType === 'product-card';
          const fallbackUrl = output?.fallbackUrl ||
            (isProductCard
              ? `https://placehold.co/400x400/e5e7eb/6b7280?text=Image+Error`
              : `https://placehold.co/800x450/e5e7eb/6b7280?text=Image+Error`);

          if (placeholder && output?.imageId) {
            imageUrlMap.set(output.imageId, fallbackUrl);
          }

          logger.warn("Image generation failed", {
            imageId: output?.imageId,
            error: output?.error,
          });
        }
      }

      // Update progress
      await db.update(generationJobs)
        .set({
          completedImages: successfulImages + failedImages,
          phase: "finalizing",
          progress: 90,
          updatedAt: new Date(),
        })
        .where(eq(generationJobs.id, jobId));

      await progress.phase("finalizing", 90);

      // ─────────────────────────────────────────────────────────────────────────
      // ASSEMBLE FINAL HTML (Replace placeholder URLs with R2 URLs)
      // The HTML already contains good alt texts from initial generation.
      // We only need to swap out the placeholder image URLs for real R2 URLs.
      // ─────────────────────────────────────────────────────────────────────────
      logger.info("Assembling final HTML with R2 URLs (keeping existing alt texts)");

      let finalHtml = htmlWithPlaceholders;

      // ═══════════════════════════════════════════════════════════════════════════
      // [ALT-DEBUG] STEP 1: Extract and log alt texts from incoming HTML
      // ═══════════════════════════════════════════════════════════════════════════
      console.log("\n" + "═".repeat(80));
      console.log("[ALT-DEBUG] STEP 1: ALT TEXTS IN INCOMING HTML (htmlWithPlaceholders)");
      console.log("═".repeat(80));

      // Extract featured image alt
      const debugFeaturedMatch = htmlWithPlaceholders.match(/<figure[^>]*class="[^"]*scai-featured-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/i);
      const debugFeaturedAlt = debugFeaturedMatch?.[1] || 'NOT FOUND';
      console.log(`[ALT-DEBUG] Featured Image Alt: "${debugFeaturedAlt}"`);
      console.log(`[ALT-DEBUG] Featured Image Alt Length: ${debugFeaturedAlt.length} chars (target: 100-125)`);
      console.log(`[ALT-DEBUG] Featured Image Alt VALID: ${debugFeaturedAlt.length >= 100 && debugFeaturedAlt.length <= 125 ? '✓ YES' : '✗ NO'}`);

      // Extract H2 image alts
      const debugH2Matches = [...htmlWithPlaceholders.matchAll(/<figure[^>]*class="[^"]*scai-h2-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/gi)];
      console.log(`[ALT-DEBUG] H2 Images Found: ${debugH2Matches.length}`);
      debugH2Matches.forEach((match, idx) => {
        const alt = match[1];
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1}: "${alt}"`);
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1} Length: ${alt.length} chars (target: 80-100)`);
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1} VALID: ${alt.length >= 80 && alt.length <= 100 ? '✓ YES' : '✗ NO'}`);
      });
      console.log("─".repeat(80));

      // Replace placeholder URLs with actual R2 URLs - keep existing alt texts from HTML
      for (const placeholder of imagePlaceholders) {
        const url = imageUrlMap.get(placeholder.imageId);
        if (url) {
          logger.info(`Updating image URL for ${placeholder.imageId}:`, {
            newUrl: url.substring(0, 60) + '...',
          });

          // Simple src URL replacement - preserve the alt text already in HTML
          // Match img tags with this data-image-id and replace only the src attribute
          const srcPattern = new RegExp(
            `(<img[^>]*data-image-id="${placeholder.imageId}"[^>]*src=")[^"]*(")`,
            "gi"
          );
          finalHtml = finalHtml.replace(srcPattern, `$1${url}$2`);

          // Also try matching by placeholder URL pattern (Loading+Image+N)
          // imageId format: img_TIMESTAMP_COUNTER_RANDOM — extract COUNTER (2nd number)
          const counterMatch = placeholder.imageId.match(/^img_\d+_(\d+)_/)
          const imageNumber = counterMatch?.[1] || '\\d+'
          const placeholderUrlPattern = new RegExp(
            `https://placehold\\.co/[^"]*Loading[+%20]Image[+%20]${imageNumber}(?!\\d)[^"]*`,
            "gi"
          );
          finalHtml = finalHtml.replace(placeholderUrlPattern, url);

          // Legacy {{IMAGE:...}} patterns (if any exist)
          const legacyPlaceholderPattern = new RegExp(
            `\\{\\{IMAGE:${placeholder.imageId}:[^}]*\\}\\}`,
            "g"
          );
          if (legacyPlaceholderPattern.test(finalHtml)) {
            finalHtml = finalHtml.replace(legacyPlaceholderPattern,
              `<img src="${url}" alt="${escapeHtml(placeholder.description)}" loading="lazy" data-image-id="${placeholder.imageId}" />`
            );
          }
        }
      }

      // ─────────────────────────────────────────────────────────────────────────
      // SAFETY NET: Replace any remaining placehold.co URLs sequentially
      // If the regex-based strategies above failed for any images, this ensures
      // no placeholder URLs remain in the final HTML saved to the database.
      // ─────────────────────────────────────────────────────────────────────────
      if (finalHtml.includes('placehold.co')) {
        logger.warn("Found remaining placehold.co URLs after primary replacement, applying sequential fallback");
        const remainingCount = (finalHtml.match(/placehold\.co/g) || []).length;
        logger.info(`Remaining placehold.co URLs: ${remainingCount}`);

        // Build an ordered list of R2 URLs from successfully generated images
        const orderedR2Urls: string[] = [];
        for (const placeholder of imagePlaceholders) {
          const url = imageUrlMap.get(placeholder.imageId);
          if (url) orderedR2Urls.push(url);
        }

        // Replace remaining placehold.co URLs sequentially
        for (const r2Url of orderedR2Urls) {
          if (!finalHtml.includes('placehold.co')) break;
          finalHtml = finalHtml.replace(
            /https:\/\/placehold\.co\/[^"'\s)]+/,
            r2Url
          );
        }

        const stillRemaining = (finalHtml.match(/placehold\.co/g) || []).length;
        if (stillRemaining > 0) {
          logger.warn(`${stillRemaining} placehold.co URLs still remain (not enough R2 URLs to replace them all)`);
        } else {
          logger.info("All placehold.co URLs successfully replaced via sequential fallback");
        }
      }

      // ═══════════════════════════════════════════════════════════════════════════
      // [ALT-DEBUG] STEP 2: Verify alt texts after URL replacement
      // ═══════════════════════════════════════════════════════════════════════════
      console.log("\n" + "═".repeat(80));
      console.log("[ALT-DEBUG] STEP 2: ALT TEXTS AFTER URL REPLACEMENT (should be unchanged)");
      console.log("═".repeat(80));

      const debugFeaturedMatch2 = finalHtml.match(/<figure[^>]*class="[^"]*scai-featured-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/i);
      const debugFeaturedAlt2 = debugFeaturedMatch2?.[1] || 'NOT FOUND';
      console.log(`[ALT-DEBUG] Featured Image Alt: "${debugFeaturedAlt2}"`);
      console.log(`[ALT-DEBUG] Featured Image Alt Length: ${debugFeaturedAlt2.length} chars`);
      console.log(`[ALT-DEBUG] Featured Alt CHANGED: ${debugFeaturedAlt !== debugFeaturedAlt2 ? '⚠️ YES (BAD!)' : '✓ NO (GOOD)'}`);

      const debugH2Matches2 = [...finalHtml.matchAll(/<figure[^>]*class="[^"]*scai-h2-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/gi)];
      debugH2Matches2.forEach((match, idx) => {
        const alt = match[1];
        const originalAlt = debugH2Matches[idx]?.[1] || '';
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1}: "${alt}" (${alt.length} chars)`);
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1} CHANGED: ${originalAlt !== alt ? '⚠️ YES (BAD!)' : '✓ NO (GOOD)'}`);
      });
      console.log("─".repeat(80));

      // ─────────────────────────────────────────────────────────────────────────
      // VALIDATE & CORRECT ALT TEXTS (if any issues exist in the HTML)
      // ─────────────────────────────────────────────────────────────────────────
      logger.info("Running final alt text validation check");

      // ═══════════════════════════════════════════════════════════════════════════
      // [ALT-DEBUG] STEP 3: Run correctAltTextsInHtml validation
      // ═══════════════════════════════════════════════════════════════════════════
      console.log("\n" + "═".repeat(80));
      console.log("[ALT-DEBUG] STEP 3: RUNNING correctAltTextsInHtml()");
      console.log("═".repeat(80));

      try {
        const costTracking = createCostTrackingContext(historyId, userId);
        const altTextResult = await correctAltTextsInHtml(finalHtml, {
          topic,
          articleType,
          provider: (payload.provider || 'gemini') as AIProvider,
          costTracking,
        });

        console.log(`[ALT-DEBUG] correctAltTextsInHtml returned:`);
        console.log(`[ALT-DEBUG]   totalCorrections: ${altTextResult.totalCorrections}`);
        console.log(`[ALT-DEBUG]   corrections array length: ${altTextResult.corrections.length}`);

        if (altTextResult.totalCorrections > 0) {
          console.log(`[ALT-DEBUG] Corrections made:`);
          altTextResult.corrections.forEach((c, idx) => {
            console.log(`[ALT-DEBUG]   Correction ${idx + 1}:`);
            console.log(`[ALT-DEBUG]     Type: ${c.imageType}`);
            console.log(`[ALT-DEBUG]     Index: ${c.imageIndex}`);
            console.log(`[ALT-DEBUG]     Original (${c.original.length} chars): "${c.original}"`);
            console.log(`[ALT-DEBUG]     Corrected (${c.corrected.length} chars): "${c.corrected}"`);
          });

          logger.info(`Applied ${altTextResult.totalCorrections} alt text corrections from final validation`, {
            corrections: altTextResult.corrections.map(c => ({
              imageType: c.imageType,
              imageIndex: c.imageIndex,
              originalLength: c.original.length,
              correctedLength: c.corrected.length,
            })),
          });
          finalHtml = altTextResult.html;
        } else {
          console.log(`[ALT-DEBUG] No corrections needed - all alt texts valid`);
          logger.info("✓ All alt texts already valid in HTML");
        }
      } catch (altTextError) {
        console.log(`[ALT-DEBUG] ⚠️ correctAltTextsInHtml THREW AN ERROR:`);
        console.log(`[ALT-DEBUG]   ${altTextError instanceof Error ? altTextError.message : 'Unknown error'}`);
        console.log(`[ALT-DEBUG]   Stack: ${altTextError instanceof Error ? altTextError.stack : 'N/A'}`);
        // Log but don't fail - alt texts in HTML from initial generation should still be usable
        logger.warn("Final alt text validation failed, proceeding with existing alt texts", {
          error: altTextError instanceof Error ? altTextError.message : "Unknown error",
        });
      }

      // ═══════════════════════════════════════════════════════════════════════════
      // [ALT-DEBUG] STEP 4: Final alt texts being saved to database
      // ═══════════════════════════════════════════════════════════════════════════
      console.log("\n" + "═".repeat(80));
      console.log("[ALT-DEBUG] STEP 4: FINAL ALT TEXTS BEING SAVED TO DATABASE");
      console.log("═".repeat(80));

      const debugFeaturedMatch3 = finalHtml.match(/<figure[^>]*class="[^"]*scai-featured-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/i);
      const debugFeaturedAlt3 = debugFeaturedMatch3?.[1] || 'NOT FOUND';
      console.log(`[ALT-DEBUG] Featured Image Alt: "${debugFeaturedAlt3}"`);
      console.log(`[ALT-DEBUG] Featured Image Alt Length: ${debugFeaturedAlt3.length} chars (target: 100-125)`);
      console.log(`[ALT-DEBUG] Featured Image Alt VALID: ${debugFeaturedAlt3.length >= 100 && debugFeaturedAlt3.length <= 125 ? '✓ YES' : '✗ NO - WILL BE SAVED INVALID!'}`);

      const debugH2Matches3 = [...finalHtml.matchAll(/<figure[^>]*class="[^"]*scai-h2-image[^"]*"[^>]*>[\s\S]*?<img[^>]*alt="([^"]*)"[^>]*>/gi)];
      console.log(`[ALT-DEBUG] H2 Images: ${debugH2Matches3.length}`);
      debugH2Matches3.forEach((match, idx) => {
        const alt = match[1];
        const isValid = alt.length >= 80 && alt.length <= 100;
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1}: "${alt}"`);
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1} Length: ${alt.length} chars (target: 80-100)`);
        console.log(`[ALT-DEBUG]   H2 Image ${idx + 1} VALID: ${isValid ? '✓ YES' : '✗ NO - WILL BE SAVED INVALID!'}`);
      });
      console.log("═".repeat(80));
      console.log("[ALT-DEBUG] END OF ALT TEXT DEBUG LOG");
      console.log("═".repeat(80) + "\n");

      // ─────────────────────────────────────────────────────────────────────────
      // FINALIZE
      // ─────────────────────────────────────────────────────────────────────────
      await finalizeArticle(
        historyId,
        finalHtml,
        wordCount,
        successfulImages,
        failedImages
      );

      // ─────────────────────────────────────────────────────────────────────────
      // UPDATE COST SUMMARY (aggregate all AI usage including images)
      // ─────────────────────────────────────────────────────────────────────────
      logger.info("Updating cost summary with all AI usage including images");
      await updateGenerationCostSummary(historyId, userId);

      // ─────────────────────────────────────────────────────────────────────────
      // FAILED IMAGE REFUND
      // Refund credits for images the user paid for but didn't receive
      // ─────────────────────────────────────────────────────────────────────────
      if (failedImages > 0 && payload.imageProvider) {
        try {
          const creditsPerImage = IMAGE_CREDIT_RATES[payload.imageProvider as keyof typeof IMAGE_CREDIT_RATES] ?? 0;
          const refundAmount = failedImages * creditsPerImage;
          if (refundAmount > 0) {
            await refundCredits(
              userId,
              refundAmount,
              historyId,
              `Failed image refund: ${failedImages} image(s) failed × ${creditsPerImage} credits`,
              'monthly'
            );
            logger.info("Credits refunded for failed images", {
              historyId,
              failedImages,
              creditsPerImage,
              refunded: refundAmount,
            });
          }
        } catch (refundError) {
          logger.error("Failed image refund error", {
            historyId,
            error: refundError instanceof Error ? refundError.message : "Unknown error",
          });
        }
      }

      // Update job as completed
      await db.update(generationJobs)
        .set({
          status: "completed",
          phase: "complete",
          progress: 100,
          completedAt: new Date(),
          updatedAt: new Date(),
        })
        .where(eq(generationJobs.id, jobId));

      // Send completion event (without finalHtml to avoid Pusher's 10KB payload limit)
      // Frontend already has all images via individual image:complete events
      await progress.complete({
        historyId,
        wordCount,
        imageCount: imagePlaceholders.length,
        successfulImages,
        failedImages,
      });

      logger.info("Article generation complete", {
        historyId,
        wordCount,
        successfulImages,
        failedImages,
      });

      return {
        success: true,
        historyId,
        finalHtml,
        wordCount,
        imageCount: imagePlaceholders.length,
        successfulImages,
        failedImages,
      };

    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : "Unknown error";
      logger.error("Orchestration failed", { jobId, error: errorMessage });

      // Update job as failed
      await db.update(generationJobs)
        .set({
          status: "failed",
          errorMessage,
          updatedAt: new Date(),
        })
        .where(eq(generationJobs.id, jobId));

      // Notify failure
      await progress.failed(errorMessage, "orchestration", historyId);

      return {
        success: false,
        historyId,
        wordCount,
        imageCount: imagePlaceholders.length,
        successfulImages: 0,
        failedImages: imagePlaceholders.length,
        error: errorMessage,
      };
    }
  },
});

// ═══════════════════════════════════════════════════════════════════════════════
// HELPER FUNCTIONS
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * Update the generation history with final HTML
 */
async function finalizeArticle(
  historyId: string,
  html: string,
  wordCount: number,
  successfulImages: number,
  failedImages: number
): Promise<void> {
  // Merge with existing metadata to preserve classificationHint etc.
  const [existing] = await db
    .select({ metadata: generationHistory.metadata })
    .from(generationHistory)
    .where(eq(generationHistory.id, historyId))
    .limit(1);

  let existingMeta: Record<string, unknown> = {};
  try {
    if (existing?.metadata) existingMeta = JSON.parse(existing.metadata);
  } catch { /* ignore */ }

  const metadata = JSON.stringify({
    ...existingMeta,
    imageStats: {
      total: successfulImages + failedImages,
      successful: successfulImages,
      failed: failedImages,
    },
    completedAt: new Date().toISOString(),
    version: "trigger-r2-v1",
  });

  await db.update(generationHistory)
    .set({
      htmlContent: html,
      wordCount,
      status: "completed",
      metadata,
      updatedAt: new Date(),
    })
    .where(eq(generationHistory.id, historyId));
}

/**
 * Escape HTML special characters
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}
