/**
 * AI Schema Index
 * 
 * Exports all Zod schemas for AI-generated content validation.
 * These schemas are used with Vercel AI SDK's generateObject() for structured outputs.
 */

// Structure schemas (H1, H2, FAQ, Meta)
export {
  H1Schema,
  createH1SchemaWithKeyword,
  H2Schema,
  FaqH2Schema,
  FaqQuestionSchema,
  ClosingH2Schema,
  HonorableMentionsH2Schema,
  WhyChooseLocalH2Schema,
  QuickFactsH2Schema,
  RatingH2Schema,
  MetaTitleSchema,
  MetaDescriptionSchema,
  FeaturedImageAltSchema,
  H2ImageAltSchema,
  StructureOutputSchema,
  StructureOutputSchemaRelaxed,
  fixStructureImageAlts,
  PartialStructureSchema,
  validateStructure,
  formatStructureErrors,
  type StructureOutput,
  type PartialStructure,
} from './structure'

// Content schemas (paragraphs, answers)
export {
  OverviewParagraphSchema,
  OverviewTextSchema,
  StandardParagraphSchema,
  StandardTextSchema,
  ClosingParagraphSchema,
  FaqAnswerSchema,
  FaqAnswersSchema,
  TopicOverviewSchema,
  SectionContentSchema,
  QuickVerdictSchema,
  KeyTakeawaysSchema as ContentKeyTakeawaysSchema,
  RatingParagraphSchema,
  HonorableMentionItemSchema,
  HonorableMentionsSchema as ContentHonorableMentionsSchema,
  ArticleContentSchema,
  StreamingContentSchema,
  analyzeContentWordCounts,
  validateContentWordCounts,
  type SectionContent,
  type ArticleContent,
  type StreamingContent,
} from './content'

// Component schemas (unique components per article type)
export {
  ProductCardSchema,
  FeatureListSchema,
  CtaBoxSchema,
  ComparisonTableSchema,
  ProsConsSchema,
  RatingContentSchema,
  ComparisonExtractSchema,
  CommercialExtractSchema,
  IngredientsSchema,
  InstructionsSchema,
  NutritionTableSchema,
  TipsParagraphSchema,
  MaterialsBoxSchema,
  ProTipsSchema,
  KeyTakeawaysSchema,
  QuickFactsSchema,
  WhyChooseLocalSchema,
  ServiceInfoSchema,
  HonorableMentionsSchema,
  UniqueComponentSchema,
  COMPONENT_SCHEMAS,
  getComponentSchema,
  validateComponentData,
  type ProductCard,
  type FeatureList,
  type CtaBox,
  type ComparisonTable,
  type ProsCons,
  type RatingContent,
  type ComparisonExtract,
  type CommercialExtract,
  type Ingredients,
  type Instructions,
  type NutritionTable,
  type MaterialsBox,
  type ProTips,
  type KeyTakeaways,
  type QuickFacts,
  type WhyChooseLocal,
  type ServiceInfo,
  type HonorableMentions,
  type UniqueComponent,
} from './components'
// Keyword schemas (keyword expansion and density tracking)
export {
  KeywordSchema,
  KeywordClusterSchema,
  KeywordArraySchema,
  CategorizedKeywordClusterSchema,
  KeywordDensitySchema,
  KeywordTrackingReportSchema,
  type Keyword,
  type KeywordCluster,
  type KeywordArray,
  type CategorizedKeywordCluster,
  type KeywordDensity,
  type KeywordTrackingReport,
} from './keywords'